import Foundation

struct MockRecipes {
    
    static let all: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Avocado Toast",
            imageURL: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600",
            cuisine: "American",
            mealType: .breakfast,
            cookingTimeMinutes: 10,
            reviewCount: 30,
            servings: 1,
            rating: 5,
            ingredients: [Ingredient(name: "2 slices sourdough", quantity: ""), Ingredient(name: "1 avocado", quantity: ""), Ingredient(name: "salt", quantity: ""), Ingredient(name: "chili flakes", quantity: ""), Ingredient(name: "lemon juice", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Toast bread."), RecipeStep(title: "Step 2", description: "Mash avocado with lemon juice and salt."), RecipeStep(title: "Step 3", description: "Spread on toast."), RecipeStep(title: "Step 4", description: "Top with chili flakes.")],
            authorUsername: "healthybites",
            isPublic: true,
            isTrending: true,
            tags: ["quick", "vegetarian", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Classic French Omelette",
            imageURL: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600",
            cuisine: "French",
            mealType: .breakfast,
            prepTime: 10,
            calories: 280,
            servings: 1,
            ingredients: [Ingredient(name: "3 eggs", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "salt", quantity: ""), Ingredient(name: "chives", quantity: ""), Ingredient(name: "cheddar", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Whisk eggs. Melt butter in pan. Add eggs and fold gently. Add cheese before folding.")],
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["classic", "quick", "french"]
        ),
        Recipe(
            id: UUID(),
            title: "Acai Smoothie Bowl",
            imageURL: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600",
            cuisine: "Brazilian",
            mealType: .breakfast,
            prepTime: 15,
            calories: 410,
            servings: 1,
            ingredients: [Ingredient(name: "acai pack", quantity: ""), Ingredient(name: "banana", quantity: ""), Ingredient(name: "almond milk", quantity: ""), Ingredient(name: "granola", quantity: ""), Ingredient(name: "berries", quantity: ""), Ingredient(name: "honey", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Blend acai with banana and almond milk. Pour into bowl. Top with granola, berries, and honey.")],
            authorUsername: "tropicaleats",
            isPublic: true,
            isTrending: true,
            tags: ["bowl", "fruity", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Fluffy Blueberry Pancakes",
            imageURL: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 20,
            calories: 520,
            servings: 2,
            ingredients: [Ingredient(name: "flour", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "milk", quantity: ""), Ingredient(name: "baking powder", quantity: ""), Ingredient(name: "blueberries", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "maple syrup", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix dry ingredients. Whisk in wet. Fold in blueberries. Cook on buttered pan until golden.")],
            authorUsername: "sundaybrunch",
            isPublic: true,
            isTrending: true,
            tags: ["sweet", "weekend", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Overnight Oats",
            imageURL: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 5,
            calories: 380,
            servings: 1,
            ingredients: [Ingredient(name: "rolled oats", quantity: ""), Ingredient(name: "almond milk", quantity: ""), Ingredient(name: "chia seeds", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "vanilla", quantity: ""), Ingredient(name: "berries", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix oats, milk, chia seeds, honey and vanilla. Refrigerate overnight. Top with berries to serve.")],
            authorUsername: "mealprepsunday",
            isPublic: true,
            isTrending: true,
            tags: ["meal prep", "no-cook", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Shakshuka",
            imageURL: "https://images.unsplash.com/photo-1588684650873-fc2cefa9fd23?w=600",
            cuisine: "Middle Eastern",
            mealType: .breakfast,
            prepTime: 25,
            calories: 340,
            servings: 2,
            ingredients: [Ingredient(name: "eggs", quantity: ""), Ingredient(name: "canned tomatoes", quantity: ""), Ingredient(name: "red pepper", quantity: ""), Ingredient(name: "onion", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "cumin", quantity: ""), Ingredient(name: "paprika", quantity: ""), Ingredient(name: "feta", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Sauté onion, pepper, garlic. Add spices and tomatoes. Simmer. Create wells and crack in eggs. Cover until set.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["eggs", "spicy", "one-pan"]
        ),
        Recipe(
            id: UUID(),
            title: "Greek Yoghurt Parfait",
            imageURL: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
            cuisine: "Greek",
            mealType: .breakfast,
            prepTime: 5,
            calories: 290,
            servings: 1,
            ingredients: [Ingredient(name: "greek yoghurt", quantity: ""), Ingredient(name: "granola", quantity: ""), Ingredient(name: "mixed berries", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "almonds", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Layer yoghurt, granola and berries in a glass. Drizzle honey and scatter almonds on top.")],
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["quick", "no-cook", "protein"]
        ),
        Recipe(
            id: UUID(),
            title: "Banana Bread",
            imageURL: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 60,
            calories: 460,
            servings: 8,
            ingredients: [Ingredient(name: "ripe bananas", quantity: ""), Ingredient(name: "flour", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "sugar", quantity: ""), Ingredient(name: "baking soda", quantity: ""), Ingredient(name: "vanilla", quantity: ""), Ingredient(name: "walnuts", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mash bananas. Mix in butter, sugar, eggs and vanilla. Fold in flour and baking soda. Bake 55 mins at 175°C.")],
            authorUsername: "bakingwithgrace",
            isPublic: true,
            isTrending: false,
            tags: ["baking", "sweet", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Smoked Salmon Bagel",
            imageURL: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 10,
            calories: 490,
            servings: 1,
            ingredients: [Ingredient(name: "bagel", quantity: ""), Ingredient(name: "cream cheese", quantity: ""), Ingredient(name: "smoked salmon", quantity: ""), Ingredient(name: "capers", quantity: ""), Ingredient(name: "red onion", quantity: ""), Ingredient(name: "dill", quantity: ""), Ingredient(name: "lemon", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Toast bagel. Spread cream cheese. Layer salmon, capers, red onion and dill. Squeeze lemon.")],
            authorUsername: "brunchclub",
            isPublic: true,
            isTrending: true,
            tags: ["quick", "protein", "brunch"]
        ),
        Recipe(
            id: UUID(),
            title: "Chia Pudding",
            imageURL: "https://images.unsplash.com/photo-1546039907-7fa05f864c02?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 5,
            calories: 310,
            servings: 1,
            ingredients: [Ingredient(name: "chia seeds", quantity: ""), Ingredient(name: "coconut milk", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "vanilla", quantity: ""), Ingredient(name: "mango", quantity: ""), Ingredient(name: "kiwi", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix chia seeds with coconut milk, honey and vanilla. Refrigerate 4 hours. Top with mango and kiwi.")],
            authorUsername: "tropicaleats",
            isPublic: true,
            isTrending: false,
            tags: ["no-cook", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Eggs Benedict",
            imageURL: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 30,
            calories: 590,
            servings: 2,
            ingredients: [Ingredient(name: "english muffins", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "ham", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "egg yolks", quantity: ""), Ingredient(name: "lemon juice", quantity: ""), Ingredient(name: "cayenne", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Poach eggs. Toast muffins. Make hollandaise with yolks, butter and lemon. Assemble and season.")],
            authorUsername: "brunchclub",
            isPublic: true,
            isTrending: true,
            tags: ["brunch", "classic", "eggs"]
        ),
        Recipe(
            id: UUID(),
            title: "Matcha Latte Oatmeal",
            imageURL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
            cuisine: "Japanese",
            mealType: .breakfast,
            prepTime: 10,
            calories: 350,
            servings: 1,
            ingredients: [Ingredient(name: "rolled oats", quantity: ""), Ingredient(name: "matcha powder", quantity: ""), Ingredient(name: "oat milk", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "banana", quantity: ""), Ingredient(name: "sesame seeds", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Cook oats in oat milk. Stir in matcha and honey. Top with sliced banana and sesame seeds.")],
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["matcha", "healthy", "japanese"]
        ),

        // MARK: — Lunch (14)
        Recipe(
            id: UUID(),
            title: "Greek Salad",
            imageURL: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600",
            cuisine: "Greek",
            mealType: .lunch,
            prepTime: 15,
            calories: 290,
            servings: 2,
            ingredients: [Ingredient(name: "cucumber", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "red onion", quantity: ""), Ingredient(name: "kalamata olives", quantity: ""), Ingredient(name: "feta", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "oregano", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Chop vegetables. Combine in bowl. Top with feta and olives. Drizzle olive oil and oregano.")],
            authorUsername: "mediterraneankitchen",
            isPublic: true,
            isTrending: false,
            tags: ["salad", "light", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Caesar Wrap",
            imageURL: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 20,
            calories: 480,
            servings: 1,
            ingredients: [Ingredient(name: "tortilla wrap", quantity: ""), Ingredient(name: "chicken breast", quantity: ""), Ingredient(name: "romaine lettuce", quantity: ""), Ingredient(name: "caesar dressing", quantity: ""), Ingredient(name: "parmesan", quantity: ""), Ingredient(name: "croutons", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Grill chicken and slice. Toss lettuce with dressing. Fill wrap and roll tight.")],
            authorUsername: "lunchboxpro",
            isPublic: true,
            isTrending: false,
            tags: ["wrap", "protein", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Spicy Tuna Sushi Bowl",
            imageURL: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600",
            cuisine: "Japanese",
            mealType: .lunch,
            prepTime: 25,
            calories: 520,
            servings: 1,
            ingredients: [Ingredient(name: "sushi rice", quantity: ""), Ingredient(name: "tuna", quantity: ""), Ingredient(name: "sriracha mayo", quantity: ""), Ingredient(name: "cucumber", quantity: ""), Ingredient(name: "avocado", quantity: ""), Ingredient(name: "soy sauce", quantity: ""), Ingredient(name: "sesame seeds", quantity: ""), Ingredient(name: "nori", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Cook sushi rice. Dice tuna and mix with sriracha mayo. Assemble bowl with toppings.")],
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["bowl", "japanese", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "Lentil Soup",
            imageURL: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 40,
            calories: 350,
            servings: 4,
            ingredients: [Ingredient(name: "red lentils", quantity: ""), Ingredient(name: "onion", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "cumin", quantity: ""), Ingredient(name: "turmeric", quantity: ""), Ingredient(name: "vegetable stock", quantity: ""), Ingredient(name: "lemon", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Sauté onion and garlic. Add spices. Pour in lentils and stock. Simmer 30 mins. Blend partially.")],
            authorUsername: "soupseason",
            isPublic: true,
            isTrending: false,
            tags: ["soup", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Caprese Sandwich",
            imageURL: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600",
            cuisine: "Italian",
            mealType: .lunch,
            prepTime: 10,
            calories: 420,
            servings: 1,
            ingredients: [Ingredient(name: "ciabatta", quantity: ""), Ingredient(name: "fresh mozzarella", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "basil", quantity: ""), Ingredient(name: "balsamic glaze", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "salt", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Slice bread. Layer mozzarella, tomato and basil. Drizzle with balsamic and olive oil. Season.")],
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["sandwich", "italian", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Miso Ramen",
            imageURL: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600",
            cuisine: "Japanese",
            mealType: .lunch,
            prepTime: 35,
            calories: 560,
            servings: 2,
            ingredients: [Ingredient(name: "ramen noodles", quantity: ""), Ingredient(name: "miso paste", quantity: ""), Ingredient(name: "soft boiled eggs", quantity: ""), Ingredient(name: "nori", quantity: ""), Ingredient(name: "corn", quantity: ""), Ingredient(name: "spring onion", quantity: ""), Ingredient(name: "sesame oil", quantity: ""), Ingredient(name: "chicken stock", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Simmer stock with miso. Cook noodles. Assemble bowls with toppings and pour over broth.")],
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["soup", "japanese", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Falafel Bowl",
            imageURL: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb4?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 30,
            calories: 490,
            servings: 2,
            ingredients: [Ingredient(name: "chickpeas", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "cumin", quantity: ""), Ingredient(name: "coriander", quantity: ""), Ingredient(name: "parsley", quantity: ""), Ingredient(name: "tahini", quantity: ""), Ingredient(name: "lemon", quantity: ""), Ingredient(name: "pita", quantity: ""), Ingredient(name: "salad", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Blend chickpeas with herbs and spices. Shape and fry until golden. Serve over salad with tahini.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["vegan", "middle eastern", "bowl"]
        ),
        Recipe(
            id: UUID(),
            title: "BLT Club Sandwich",
            imageURL: "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 15,
            calories: 540,
            servings: 1,
            ingredients: [Ingredient(name: "white bread", quantity: ""), Ingredient(name: "bacon", quantity: ""), Ingredient(name: "lettuce", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "mayo", quantity: ""), Ingredient(name: "cheddar", quantity: ""), Ingredient(name: "turkey", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Toast bread. Cook bacon until crispy. Layer with mayo, lettuce, tomato, cheese and turkey.")],
            authorUsername: "lunchboxpro",
            isPublic: true,
            isTrending: false,
            tags: ["sandwich", "classic", "american"]
        ),
        Recipe(
            id: UUID(),
            title: "Pad Thai",
            imageURL: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600",
            cuisine: "Thai",
            mealType: .lunch,
            prepTime: 30,
            calories: 580,
            servings: 2,
            ingredients: [Ingredient(name: "rice noodles", quantity: ""), Ingredient(name: "prawns", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "bean sprouts", quantity: ""), Ingredient(name: "peanuts", quantity: ""), Ingredient(name: "fish sauce", quantity: ""), Ingredient(name: "tamarind", quantity: ""), Ingredient(name: "lime", quantity: ""), Ingredient(name: "spring onion", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Soak noodles. Stir fry prawns. Add eggs and scramble. Toss in noodles, sauce and sprouts. Top with peanuts.")],
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: true,
            tags: ["thai", "noodles", "stir fry"]
        ),
        Recipe(
            id: UUID(),
            title: "Roasted Veggie Quinoa Bowl",
            imageURL: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 35,
            calories: 430,
            servings: 2,
            ingredients: [Ingredient(name: "quinoa", quantity: ""), Ingredient(name: "sweet potato", quantity: ""), Ingredient(name: "broccoli", quantity: ""), Ingredient(name: "chickpeas", quantity: ""), Ingredient(name: "tahini", quantity: ""), Ingredient(name: "lemon", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "olive oil", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Roast veggies and chickpeas at 200°C. Cook quinoa. Make tahini dressing. Assemble bowl.")],
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["bowl", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Tom Yum Soup",
            imageURL: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600",
            cuisine: "Thai",
            mealType: .lunch,
            prepTime: 30,
            calories: 310,
            servings: 2,
            ingredients: [Ingredient(name: "prawns", quantity: ""), Ingredient(name: "lemongrass", quantity: ""), Ingredient(name: "kaffir lime leaves", quantity: ""), Ingredient(name: "galangal", quantity: ""), Ingredient(name: "mushrooms", quantity: ""), Ingredient(name: "fish sauce", quantity: ""), Ingredient(name: "lime juice", quantity: ""), Ingredient(name: "chili", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Simmer stock with lemongrass, galangal and lime leaves. Add mushrooms and prawns. Season with fish sauce and lime.")],
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: false,
            tags: ["soup", "thai", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Shawarma Plate",
            imageURL: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 40,
            calories: 610,
            servings: 2,
            ingredients: [Ingredient(name: "chicken thighs", quantity: ""), Ingredient(name: "shawarma spices", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "lemon", quantity: ""), Ingredient(name: "yoghurt", quantity: ""), Ingredient(name: "flatbread", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "parsley", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Marinate chicken in spices and lemon. Grill until charred. Serve with flatbread, tomato and garlic sauce.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["middle eastern", "protein", "grilled"]
        ),
        Recipe(
            id: UUID(),
            title: "Nicoise Salad",
            imageURL: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600",
            cuisine: "French",
            mealType: .lunch,
            prepTime: 25,
            calories: 410,
            servings: 2,
            ingredients: [Ingredient(name: "tuna", quantity: ""), Ingredient(name: "green beans", quantity: ""), Ingredient(name: "boiled eggs", quantity: ""), Ingredient(name: "cherry tomatoes", quantity: ""), Ingredient(name: "olives", quantity: ""), Ingredient(name: "potato", quantity: ""), Ingredient(name: "dijon mustard", quantity: ""), Ingredient(name: "olive oil", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Boil potatoes, eggs and beans. Arrange on plate with tuna, tomatoes and olives. Whisk dressing and pour over.")],
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["salad", "french", "protein"]
        ),
        Recipe(
            id: UUID(),
            title: "Korean Bibimbap",
            imageURL: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600",
            cuisine: "Korean",
            mealType: .lunch,
            prepTime: 40,
            calories: 550,
            servings: 2,
            ingredients: [Ingredient(name: "rice", quantity: ""), Ingredient(name: "beef mince", quantity: ""), Ingredient(name: "spinach", quantity: ""), Ingredient(name: "carrot", quantity: ""), Ingredient(name: "zucchini", quantity: ""), Ingredient(name: "egg", quantity: ""), Ingredient(name: "gochujang", quantity: ""), Ingredient(name: "sesame oil", quantity: ""), Ingredient(name: "soy sauce", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Cook rice. Sauté vegetables separately. Brown beef with soy sauce. Assemble bowl. Top with fried egg and gochujang.")],
            authorUsername: "seoulkitchen",
            isPublic: true,
            isTrending: true,
            tags: ["korean", "bowl", "rice"]
        ),

        // MARK: — Dinner (16)
        Recipe(
            id: UUID(),
            title: "Spaghetti Carbonara",
            imageURL: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 25,
            calories: 680,
            servings: 2,
            ingredients: [Ingredient(name: "spaghetti", quantity: ""), Ingredient(name: "pancetta", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "parmesan", quantity: ""), Ingredient(name: "black pepper", quantity: ""), Ingredient(name: "salt", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Cook pasta. Fry pancetta. Mix eggs and parmesan. Toss hot pasta off heat with egg mixture.")],
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: true,
            tags: ["pasta", "italian", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Butter Chicken",
            imageURL: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600",
            cuisine: "Indian",
            mealType: .dinner,
            prepTime: 45,
            calories: 620,
            servings: 4,
            ingredients: [Ingredient(name: "chicken thighs", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "tomato puree", quantity: ""), Ingredient(name: "cream", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "ginger", quantity: ""), Ingredient(name: "garam masala", quantity: ""), Ingredient(name: "cumin", quantity: ""), Ingredient(name: "rice", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Marinate chicken. Sauté garlic and ginger. Add spices and tomato. Simmer chicken. Finish with cream and butter.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["curry", "indian", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Tacos",
            imageURL: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
            cuisine: "Mexican",
            mealType: .dinner,
            prepTime: 30,
            calories: 560,
            servings: 3,
            ingredients: [Ingredient(name: "corn tortillas", quantity: ""), Ingredient(name: "beef mince", quantity: ""), Ingredient(name: "taco seasoning", quantity: ""), Ingredient(name: "cheddar", quantity: ""), Ingredient(name: "sour cream", quantity: ""), Ingredient(name: "salsa", quantity: ""), Ingredient(name: "avocado", quantity: ""), Ingredient(name: "lime", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Brown beef with seasoning. Warm tortillas. Fill with beef and toppings. Serve with lime.")],
            authorUsername: "mexicanfeast",
            isPublic: true,
            isTrending: true,
            tags: ["mexican", "tacos", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Salmon Teriyaki",
            imageURL: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600",
            cuisine: "Japanese",
            mealType: .dinner,
            prepTime: 20,
            calories: 490,
            servings: 2,
            ingredients: [Ingredient(name: "salmon fillets", quantity: ""), Ingredient(name: "soy sauce", quantity: ""), Ingredient(name: "mirin", quantity: ""), Ingredient(name: "sake", quantity: ""), Ingredient(name: "sugar", quantity: ""), Ingredient(name: "steamed rice", quantity: ""), Ingredient(name: "sesame seeds", quantity: ""), Ingredient(name: "spring onion", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix teriyaki sauce. Marinate salmon 15 mins. Pan fry skin-side down. Glaze with sauce. Serve over rice.")],
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["japanese", "fish", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Bourguignon",
            imageURL: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600",
            cuisine: "French",
            mealType: .dinner,
            prepTime: 180,
            calories: 720,
            servings: 6,
            ingredients: [Ingredient(name: "beef chuck", quantity: ""), Ingredient(name: "red wine", quantity: ""), Ingredient(name: "bacon", quantity: ""), Ingredient(name: "mushrooms", quantity: ""), Ingredient(name: "pearl onions", quantity: ""), Ingredient(name: "carrots", quantity: ""), Ingredient(name: "thyme", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "beef stock", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Brown beef and bacon. Deglaze with wine. Add vegetables and stock. Braise in oven at 160°C for 2.5 hours.")],
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["french", "slow cook", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Tikka Masala",
            imageURL: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
            cuisine: "Indian",
            mealType: .dinner,
            prepTime: 50,
            calories: 640,
            servings: 4,
            ingredients: [Ingredient(name: "chicken breast", quantity: ""), Ingredient(name: "yoghurt", quantity: ""), Ingredient(name: "tikka masala paste", quantity: ""), Ingredient(name: "canned tomatoes", quantity: ""), Ingredient(name: "cream", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "ginger", quantity: ""), Ingredient(name: "naan", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Marinate chicken in yoghurt and spices. Grill. Simmer in tomato and cream sauce. Serve with naan.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["indian", "curry", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Margherita Pizza",
            imageURL: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 60,
            calories: 700,
            servings: 2,
            ingredients: [Ingredient(name: "pizza dough", quantity: ""), Ingredient(name: "san marzano tomatoes", quantity: ""), Ingredient(name: "fresh mozzarella", quantity: ""), Ingredient(name: "basil", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "salt", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Stretch dough. Spread crushed tomatoes. Top with torn mozzarella. Bake at 250°C for 10 mins. Add fresh basil.")],
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: true,
            tags: ["pizza", "italian", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Lamb Kofta",
            imageURL: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
            cuisine: "Middle Eastern",
            mealType: .dinner,
            prepTime: 35,
            calories: 580,
            servings: 4,
            ingredients: [Ingredient(name: "lamb mince", quantity: ""), Ingredient(name: "onion", quantity: ""), Ingredient(name: "cumin", quantity: ""), Ingredient(name: "coriander", quantity: ""), Ingredient(name: "cinnamon", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "flatbread", quantity: ""), Ingredient(name: "tzatziki", quantity: ""), Ingredient(name: "salad", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix lamb with spices. Shape onto skewers. Grill until charred. Serve with flatbread and tzatziki.")],
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: false,
            tags: ["middle eastern", "grilled", "lamb"]
        ),
        Recipe(
            id: UUID(),
            title: "Mushroom Risotto",
            imageURL: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 45,
            calories: 590,
            servings: 2,
            ingredients: [Ingredient(name: "arborio rice", quantity: ""), Ingredient(name: "mixed mushrooms", quantity: ""), Ingredient(name: "white wine", quantity: ""), Ingredient(name: "parmesan", quantity: ""), Ingredient(name: "butter", quantity: ""), Ingredient(name: "shallots", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "thyme", quantity: ""), Ingredient(name: "stock", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Sauté shallots and garlic. Toast rice. Add wine. Add stock ladle by ladle stirring constantly. Fold in butter and parmesan.")],
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["italian", "vegetarian", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Green Thai Curry",
            imageURL: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600",
            cuisine: "Thai",
            mealType: .dinner,
            prepTime: 35,
            calories: 550,
            servings: 3,
            ingredients: [Ingredient(name: "chicken", quantity: ""), Ingredient(name: "green curry paste", quantity: ""), Ingredient(name: "coconut milk", quantity: ""), Ingredient(name: "thai eggplant", quantity: ""), Ingredient(name: "bamboo shoots", quantity: ""), Ingredient(name: "kaffir lime leaves", quantity: ""), Ingredient(name: "fish sauce", quantity: ""), Ingredient(name: "jasmine rice", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Fry curry paste in coconut cream. Add chicken. Pour in coconut milk. Add vegetables and simmer. Serve with rice.")],
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: true,
            tags: ["thai", "curry", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "BBQ Pulled Pork",
            imageURL: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600",
            cuisine: "American",
            mealType: .dinner,
            prepTime: 360,
            calories: 680,
            servings: 6,
            ingredients: [Ingredient(name: "pork shoulder", quantity: ""), Ingredient(name: "bbq sauce", quantity: ""), Ingredient(name: "brown sugar", quantity: ""), Ingredient(name: "paprika", quantity: ""), Ingredient(name: "garlic powder", quantity: ""), Ingredient(name: "onion powder", quantity: ""), Ingredient(name: "brioche buns", quantity: ""), Ingredient(name: "coleslaw", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Rub pork with spice mix. Slow cook 6 hours at 140°C. Shred with forks. Toss in BBQ sauce. Serve in brioche buns.")],
            authorUsername: "pitmaster_aus",
            isPublic: true,
            isTrending: true,
            tags: ["american", "slow cook", "bbq"]
        ),
        Recipe(
            id: UUID(),
            title: "Prawn Stir Fry",
            imageURL: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
            cuisine: "Chinese",
            mealType: .dinner,
            prepTime: 20,
            calories: 420,
            servings: 2,
            ingredients: [Ingredient(name: "prawns", quantity: ""), Ingredient(name: "bok choy", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "ginger", quantity: ""), Ingredient(name: "oyster sauce", quantity: ""), Ingredient(name: "soy sauce", quantity: ""), Ingredient(name: "sesame oil", quantity: ""), Ingredient(name: "rice", quantity: ""), Ingredient(name: "spring onion", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Stir fry garlic and ginger. Add prawns until pink. Add bok choy and sauce. Toss and serve over rice.")],
            authorUsername: "wokmaster",
            isPublic: true,
            isTrending: false,
            tags: ["chinese", "quick", "seafood"]
        ),
        Recipe(
            id: UUID(),
            title: "Moussaka",
            imageURL: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600",
            cuisine: "Greek",
            mealType: .dinner,
            prepTime: 90,
            calories: 660,
            servings: 6,
            ingredients: [Ingredient(name: "eggplant", quantity: ""), Ingredient(name: "lamb mince", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "cinnamon", quantity: ""), Ingredient(name: "allspice", quantity: ""), Ingredient(name: "bechamel sauce", quantity: ""), Ingredient(name: "parmesan", quantity: ""), Ingredient(name: "onion", quantity: ""), Ingredient(name: "garlic", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Fry eggplant. Make spiced lamb sauce. Layer eggplant and meat. Top with bechamel and cheese. Bake 45 mins.")],
            authorUsername: "mediterraneankitchen",
            isPublic: true,
            isTrending: false,
            tags: ["greek", "baked", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Schnitzel",
            imageURL: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600",
            cuisine: "Australian",
            mealType: .dinner,
            prepTime: 30,
            calories: 610,
            servings: 2,
            ingredients: [Ingredient(name: "chicken breast", quantity: ""), Ingredient(name: "breadcrumbs", quantity: ""), Ingredient(name: "eggs", quantity: ""), Ingredient(name: "flour", quantity: ""), Ingredient(name: "lemon", quantity: ""), Ingredient(name: "chips", quantity: ""), Ingredient(name: "salad", quantity: ""), Ingredient(name: "salt", quantity: ""), Ingredient(name: "pepper", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Pound chicken flat. Coat in flour, egg and breadcrumbs. Pan fry until golden. Serve with chips and lemon.")],
            authorUsername: "aussiegrill",
            isPublic: true,
            isTrending: true,
            tags: ["australian", "fried", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Vegetable Dumplings",
            imageURL: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
            cuisine: "Chinese",
            mealType: .dinner,
            prepTime: 50,
            calories: 380,
            servings: 4,
            ingredients: [Ingredient(name: "dumpling wrappers", quantity: ""), Ingredient(name: "cabbage", quantity: ""), Ingredient(name: "shiitake mushrooms", quantity: ""), Ingredient(name: "ginger", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "soy sauce", quantity: ""), Ingredient(name: "sesame oil", quantity: ""), Ingredient(name: "spring onion", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix filling. Place in wrappers and seal. Steam or pan fry until golden. Serve with dipping sauce.")],
            authorUsername: "wokmaster",
            isPublic: true,
            isTrending: false,
            tags: ["chinese", "dumplings", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Rendang",
            imageURL: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
            cuisine: "Malaysian",
            mealType: .dinner,
            prepTime: 120,
            calories: 690,
            servings: 4,
            ingredients: [Ingredient(name: "beef chuck", quantity: ""), Ingredient(name: "coconut milk", quantity: ""), Ingredient(name: "lemongrass", quantity: ""), Ingredient(name: "galangal", quantity: ""), Ingredient(name: "turmeric", quantity: ""), Ingredient(name: "chili", quantity: ""), Ingredient(name: "kaffir lime leaves", quantity: ""), Ingredient(name: "toasted coconut", quantity: ""), Ingredient(name: "rice", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Blend spice paste. Brown beef. Add coconut milk and paste. Simmer 1.5 hours until sauce is dry and beef is coated.")],
            authorUsername: "asianfusionkitchen",
            isPublic: true,
            isTrending: true,
            tags: ["malaysian", "slow cook", "spicy"]
        ),

        // MARK: — Snacks (8)
        Recipe(
            id: UUID(),
            title: "Hummus & Veggies",
            imageURL: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600",
            cuisine: "Middle Eastern",
            mealType: .snack,
            prepTime: 10,
            calories: 220,
            servings: 2,
            ingredients: [Ingredient(name: "chickpeas", quantity: ""), Ingredient(name: "tahini", quantity: ""), Ingredient(name: "lemon", quantity: ""), Ingredient(name: "garlic", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "paprika", quantity: ""), Ingredient(name: "carrot", quantity: ""), Ingredient(name: "celery", quantity: ""), Ingredient(name: "cucumber", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Blend chickpeas, tahini, lemon and garlic until smooth. Drizzle with olive oil and paprika. Serve with cut vegetables.")],
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "vegan", "dip"]
        ),
        Recipe(
            id: UUID(),
            title: "Energy Balls",
            imageURL: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 15,
            calories: 180,
            servings: 12,
            ingredients: [Ingredient(name: "rolled oats", quantity: ""), Ingredient(name: "peanut butter", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "dark chocolate chips", quantity: ""), Ingredient(name: "chia seeds", quantity: ""), Ingredient(name: "vanilla", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mix all ingredients. Roll into balls. Refrigerate 30 mins to set.")],
            authorUsername: "mealprepsunday",
            isPublic: true,
            isTrending: true,
            tags: ["snack", "no-bake", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Guacamole & Chips",
            imageURL: "https://images.unsplash.com/photo-1518181835702-6eef8b4b2113?w=600",
            cuisine: "Mexican",
            mealType: .snack,
            prepTime: 10,
            calories: 280,
            servings: 4,
            ingredients: [Ingredient(name: "avocado", quantity: ""), Ingredient(name: "lime", quantity: ""), Ingredient(name: "coriander", quantity: ""), Ingredient(name: "red onion", quantity: ""), Ingredient(name: "jalapeño", quantity: ""), Ingredient(name: "tomato", quantity: ""), Ingredient(name: "salt", quantity: ""), Ingredient(name: "corn chips", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Mash avocado. Mix in lime juice, onion, jalapeño and coriander. Season and serve with corn chips.")],
            authorUsername: "mexicanfeast",
            isPublic: true,
            isTrending: true,
            tags: ["mexican", "dip", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Protein Smoothie",
            imageURL: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 5,
            calories: 340,
            servings: 1,
            ingredients: [Ingredient(name: "banana", quantity: ""), Ingredient(name: "protein powder", quantity: ""), Ingredient(name: "almond milk", quantity: ""), Ingredient(name: "peanut butter", quantity: ""), Ingredient(name: "honey", quantity: ""), Ingredient(name: "ice", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Blend all ingredients until smooth. Serve immediately.")],
            authorUsername: "fitmeals",
            isPublic: true,
            isTrending: false,
            tags: ["smoothie", "protein", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Baked Kale Chips",
            imageURL: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 20,
            calories: 120,
            servings: 2,
            ingredients: [Ingredient(name: "kale", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "salt", quantity: ""), Ingredient(name: "nutritional yeast", quantity: ""), Ingredient(name: "garlic powder", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Tear kale into pieces. Toss with oil and seasoning. Bake at 175°C for 15 mins until crispy.")],
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "vegan", "low calorie"]
        ),
        Recipe(
            id: UUID(),
            title: "Caprese Skewers",
            imageURL: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600",
            cuisine: "Italian",
            mealType: .snack,
            prepTime: 10,
            calories: 200,
            servings: 4,
            ingredients: [Ingredient(name: "cherry tomatoes", quantity: ""), Ingredient(name: "fresh mozzarella balls", quantity: ""), Ingredient(name: "basil", quantity: ""), Ingredient(name: "balsamic glaze", quantity: ""), Ingredient(name: "olive oil", quantity: ""), Ingredient(name: "salt", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Thread tomato, mozzarella and basil onto skewers. Drizzle with olive oil and balsamic glaze. Season.")],
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["italian", "snack", "party"]
        ),
        Recipe(
            id: UUID(),
            title: "Edamame with Sea Salt",
            imageURL: "https://images.unsplash.com/photo-1550951234-8f8c7e5a7e3b?w=600",
            cuisine: "Japanese",
            mealType: .snack,
            prepTime: 10,
            calories: 150,
            servings: 2,
            ingredients: [Ingredient(name: "edamame pods", quantity: ""), Ingredient(name: "sea salt", quantity: ""), Ingredient(name: "sesame oil", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Boil edamame in salted water for 5 mins. Drain and toss with sea salt and a drizzle of sesame oil.")],
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: false,
            tags: ["japanese", "snack", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Apple Slices with Almond Butter",
            imageURL: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 5,
            calories: 210,
            servings: 1,
            ingredients: [Ingredient(name: "apple", quantity: ""), Ingredient(name: "almond butter", quantity: ""), Ingredient(name: "cinnamon", quantity: ""), Ingredient(name: "honey", quantity: "")],
            instructions: [RecipeStep(title: "Step 1", description: "Slice apple. Serve with almond butter for dipping. Dust with cinnamon and drizzle honey if desired.")],
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "quick", "healthy"]
        ),
    ]

    static var trending: [Recipe] {
        all.filter { $0.isTrending }
    }

    static func byMealType(_ type: MealType) -> [Recipe] {
        all.filter { $0.mealType == type.rawValue }
    }

    static func byCuisine(_ cuisine: String) -> [Recipe] {
        all.filter { $0.cuisine == cuisine }
    }

    static func search(_ query: String) -> [Recipe] {
        let q = query.lowercased()
        return all.filter {
            $0.name.lowercased().contains(q) ||
            $0.cuisine.lowercased().contains(q) ||
            $0.tags.contains(where: { $0.lowercased().contains(q) })
        }
    }
}
