import Foundation

struct MockRecipes {
    
    static let all: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Avocado Toast",
            imageURL: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600",
            cuisine: "American",
            mealType: .breakfast,
            cookingTimeMinutes: 10,
            reviewCount: 30,
            servings: 1,
            rating: 5,
            ingredients: ["2 slices sourdough", "1 avocado", "salt", "chili flakes", "lemon juice"],
            instructions: ["Toast bread.", "Mash avocado with lemon juice and salt.", "Spread on toast.", "Top with chili flakes.",],
            authorUsername: "healthybites",
            isPublic: true,
            isTrending: true,
            tags: ["quick", "vegetarian", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Classic French Omelette",
            imageURL: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600",
            cuisine: "French",
            mealType: .breakfast,
            prepTime: 10,
            calories: 280,
            servings: 1,
            ingredients: ["3 eggs", "butter", "salt", "chives", "cheddar"],
            instructions: "Whisk eggs. Melt butter in pan. Add eggs and fold gently. Add cheese before folding.",
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["classic", "quick", "french"]
        ),
        Recipe(
            id: UUID(),
            title: "Acai Smoothie Bowl",
            imageURL: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600",
            cuisine: "Brazilian",
            mealType: .breakfast,
            prepTime: 15,
            calories: 410,
            servings: 1,
            ingredients: ["acai pack", "banana", "almond milk", "granola", "berries", "honey"],
            instructions: "Blend acai with banana and almond milk. Pour into bowl. Top with granola, berries, and honey.",
            authorUsername: "tropicaleats",
            isPublic: true,
            isTrending: true,
            tags: ["bowl", "fruity", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Fluffy Blueberry Pancakes",
            imageURL: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 20,
            calories: 520,
            servings: 2,
            ingredients: ["flour", "eggs", "milk", "baking powder", "blueberries", "butter", "maple syrup"],
            instructions: "Mix dry ingredients. Whisk in wet. Fold in blueberries. Cook on buttered pan until golden.",
            authorUsername: "sundaybrunch",
            isPublic: true,
            isTrending: true,
            tags: ["sweet", "weekend", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Overnight Oats",
            imageURL: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 5,
            calories: 380,
            servings: 1,
            ingredients: ["rolled oats", "almond milk", "chia seeds", "honey", "vanilla", "berries"],
            instructions: "Mix oats, milk, chia seeds, honey and vanilla. Refrigerate overnight. Top with berries to serve.",
            authorUsername: "mealprepsunday",
            isPublic: true,
            isTrending: true,
            tags: ["meal prep", "no-cook", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Shakshuka",
            imageURL: "https://images.unsplash.com/photo-1588684650873-fc2cefa9fd23?w=600",
            cuisine: "Middle Eastern",
            mealType: .breakfast,
            prepTime: 25,
            calories: 340,
            servings: 2,
            ingredients: ["eggs", "canned tomatoes", "red pepper", "onion", "garlic", "cumin", "paprika", "feta"],
            instructions: "Sauté onion, pepper, garlic. Add spices and tomatoes. Simmer. Create wells and crack in eggs. Cover until set.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["eggs", "spicy", "one-pan"]
        ),
        Recipe(
            id: UUID(),
            title: "Greek Yoghurt Parfait",
            imageURL: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600",
            cuisine: "Greek",
            mealType: .breakfast,
            prepTime: 5,
            calories: 290,
            servings: 1,
            ingredients: ["greek yoghurt", "granola", "mixed berries", "honey", "almonds"],
            instructions: "Layer yoghurt, granola and berries in a glass. Drizzle honey and scatter almonds on top.",
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["quick", "no-cook", "protein"]
        ),
        Recipe(
            id: UUID(),
            title: "Banana Bread",
            imageURL: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 60,
            calories: 460,
            servings: 8,
            ingredients: ["ripe bananas", "flour", "eggs", "butter", "sugar", "baking soda", "vanilla", "walnuts"],
            instructions: "Mash bananas. Mix in butter, sugar, eggs and vanilla. Fold in flour and baking soda. Bake 55 mins at 175°C.",
            authorUsername: "bakingwithgrace",
            isPublic: true,
            isTrending: false,
            tags: ["baking", "sweet", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Smoked Salmon Bagel",
            imageURL: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 10,
            calories: 490,
            servings: 1,
            ingredients: ["bagel", "cream cheese", "smoked salmon", "capers", "red onion", "dill", "lemon"],
            instructions: "Toast bagel. Spread cream cheese. Layer salmon, capers, red onion and dill. Squeeze lemon.",
            authorUsername: "brunchclub",
            isPublic: true,
            isTrending: true,
            tags: ["quick", "protein", "brunch"]
        ),
        Recipe(
            id: UUID(),
            title: "Chia Pudding",
            imageURL: "https://images.unsplash.com/photo-1546039907-7fa05f864c02?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 5,
            calories: 310,
            servings: 1,
            ingredients: ["chia seeds", "coconut milk", "honey", "vanilla", "mango", "kiwi"],
            instructions: "Mix chia seeds with coconut milk, honey and vanilla. Refrigerate 4 hours. Top with mango and kiwi.",
            authorUsername: "tropicaleats",
            isPublic: true,
            isTrending: false,
            tags: ["no-cook", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Eggs Benedict",
            imageURL: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600",
            cuisine: "American",
            mealType: .breakfast,
            prepTime: 30,
            calories: 590,
            servings: 2,
            ingredients: ["english muffins", "eggs", "ham", "butter", "egg yolks", "lemon juice", "cayenne"],
            instructions: "Poach eggs. Toast muffins. Make hollandaise with yolks, butter and lemon. Assemble and season.",
            authorUsername: "brunchclub",
            isPublic: true,
            isTrending: true,
            tags: ["brunch", "classic", "eggs"]
        ),
        Recipe(
            id: UUID(),
            title: "Matcha Latte Oatmeal",
            imageURL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
            cuisine: "Japanese",
            mealType: .breakfast,
            prepTime: 10,
            calories: 350,
            servings: 1,
            ingredients: ["rolled oats", "matcha powder", "oat milk", "honey", "banana", "sesame seeds"],
            instructions: "Cook oats in oat milk. Stir in matcha and honey. Top with sliced banana and sesame seeds.",
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["matcha", "healthy", "japanese"]
        ),

        // MARK: — Lunch (14)
        Recipe(
            id: UUID(),
            title: "Greek Salad",
            imageURL: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600",
            cuisine: "Greek",
            mealType: .lunch,
            prepTime: 15,
            calories: 290,
            servings: 2,
            ingredients: ["cucumber", "tomato", "red onion", "kalamata olives", "feta", "olive oil", "oregano"],
            instructions: "Chop vegetables. Combine in bowl. Top with feta and olives. Drizzle olive oil and oregano.",
            authorUsername: "mediterraneankitchen",
            isPublic: true,
            isTrending: false,
            tags: ["salad", "light", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Caesar Wrap",
            imageURL: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 20,
            calories: 480,
            servings: 1,
            ingredients: ["tortilla wrap", "chicken breast", "romaine lettuce", "caesar dressing", "parmesan", "croutons"],
            instructions: "Grill chicken and slice. Toss lettuce with dressing. Fill wrap and roll tight.",
            authorUsername: "lunchboxpro",
            isPublic: true,
            isTrending: false,
            tags: ["wrap", "protein", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Spicy Tuna Sushi Bowl",
            imageURL: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600",
            cuisine: "Japanese",
            mealType: .lunch,
            prepTime: 25,
            calories: 520,
            servings: 1,
            ingredients: ["sushi rice", "tuna", "sriracha mayo", "cucumber", "avocado", "soy sauce", "sesame seeds", "nori"],
            instructions: "Cook sushi rice. Dice tuna and mix with sriracha mayo. Assemble bowl with toppings.",
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["bowl", "japanese", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "Lentil Soup",
            imageURL: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 40,
            calories: 350,
            servings: 4,
            ingredients: ["red lentils", "onion", "garlic", "cumin", "turmeric", "vegetable stock", "lemon"],
            instructions: "Sauté onion and garlic. Add spices. Pour in lentils and stock. Simmer 30 mins. Blend partially.",
            authorUsername: "soupseason",
            isPublic: true,
            isTrending: false,
            tags: ["soup", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Caprese Sandwich",
            imageURL: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600",
            cuisine: "Italian",
            mealType: .lunch,
            prepTime: 10,
            calories: 420,
            servings: 1,
            ingredients: ["ciabatta", "fresh mozzarella", "tomato", "basil", "balsamic glaze", "olive oil", "salt"],
            instructions: "Slice bread. Layer mozzarella, tomato and basil. Drizzle with balsamic and olive oil. Season.",
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["sandwich", "italian", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Miso Ramen",
            imageURL: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600",
            cuisine: "Japanese",
            mealType: .lunch,
            prepTime: 35,
            calories: 560,
            servings: 2,
            ingredients: ["ramen noodles", "miso paste", "soft boiled eggs", "nori", "corn", "spring onion", "sesame oil", "chicken stock"],
            instructions: "Simmer stock with miso. Cook noodles. Assemble bowls with toppings and pour over broth.",
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["soup", "japanese", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Falafel Bowl",
            imageURL: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb4?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 30,
            calories: 490,
            servings: 2,
            ingredients: ["chickpeas", "garlic", "cumin", "coriander", "parsley", "tahini", "lemon", "pita", "salad"],
            instructions: "Blend chickpeas with herbs and spices. Shape and fry until golden. Serve over salad with tahini.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["vegan", "middle eastern", "bowl"]
        ),
        Recipe(
            id: UUID(),
            title: "BLT Club Sandwich",
            imageURL: "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 15,
            calories: 540,
            servings: 1,
            ingredients: ["white bread", "bacon", "lettuce", "tomato", "mayo", "cheddar", "turkey"],
            instructions: "Toast bread. Cook bacon until crispy. Layer with mayo, lettuce, tomato, cheese and turkey.",
            authorUsername: "lunchboxpro",
            isPublic: true,
            isTrending: false,
            tags: ["sandwich", "classic", "american"]
        ),
        Recipe(
            id: UUID(),
            title: "Pad Thai",
            imageURL: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600",
            cuisine: "Thai",
            mealType: .lunch,
            prepTime: 30,
            calories: 580,
            servings: 2,
            ingredients: ["rice noodles", "prawns", "eggs", "bean sprouts", "peanuts", "fish sauce", "tamarind", "lime", "spring onion"],
            instructions: "Soak noodles. Stir fry prawns. Add eggs and scramble. Toss in noodles, sauce and sprouts. Top with peanuts.",
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: true,
            tags: ["thai", "noodles", "stir fry"]
        ),
        Recipe(
            id: UUID(),
            title: "Roasted Veggie Quinoa Bowl",
            imageURL: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600",
            cuisine: "American",
            mealType: .lunch,
            prepTime: 35,
            calories: 430,
            servings: 2,
            ingredients: ["quinoa", "sweet potato", "broccoli", "chickpeas", "tahini", "lemon", "garlic", "olive oil"],
            instructions: "Roast veggies and chickpeas at 200°C. Cook quinoa. Make tahini dressing. Assemble bowl.",
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["bowl", "vegan", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Tom Yum Soup",
            imageURL: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600",
            cuisine: "Thai",
            mealType: .lunch,
            prepTime: 30,
            calories: 310,
            servings: 2,
            ingredients: ["prawns", "lemongrass", "kaffir lime leaves", "galangal", "mushrooms", "fish sauce", "lime juice", "chili"],
            instructions: "Simmer stock with lemongrass, galangal and lime leaves. Add mushrooms and prawns. Season with fish sauce and lime.",
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: false,
            tags: ["soup", "thai", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Shawarma Plate",
            imageURL: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600",
            cuisine: "Middle Eastern",
            mealType: .lunch,
            prepTime: 40,
            calories: 610,
            servings: 2,
            ingredients: ["chicken thighs", "shawarma spices", "garlic", "lemon", "yoghurt", "flatbread", "tomato", "parsley"],
            instructions: "Marinate chicken in spices and lemon. Grill until charred. Serve with flatbread, tomato and garlic sauce.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["middle eastern", "protein", "grilled"]
        ),
        Recipe(
            id: UUID(),
            title: "Nicoise Salad",
            imageURL: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600",
            cuisine: "French",
            mealType: .lunch,
            prepTime: 25,
            calories: 410,
            servings: 2,
            ingredients: ["tuna", "green beans", "boiled eggs", "cherry tomatoes", "olives", "potato", "dijon mustard", "olive oil"],
            instructions: "Boil potatoes, eggs and beans. Arrange on plate with tuna, tomatoes and olives. Whisk dressing and pour over.",
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["salad", "french", "protein"]
        ),
        Recipe(
            id: UUID(),
            title: "Korean Bibimbap",
            imageURL: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600",
            cuisine: "Korean",
            mealType: .lunch,
            prepTime: 40,
            calories: 550,
            servings: 2,
            ingredients: ["rice", "beef mince", "spinach", "carrot", "zucchini", "egg", "gochujang", "sesame oil", "soy sauce"],
            instructions: "Cook rice. Sauté vegetables separately. Brown beef with soy sauce. Assemble bowl. Top with fried egg and gochujang.",
            authorUsername: "seoulkitchen",
            isPublic: true,
            isTrending: true,
            tags: ["korean", "bowl", "rice"]
        ),

        // MARK: — Dinner (16)
        Recipe(
            id: UUID(),
            title: "Spaghetti Carbonara",
            imageURL: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 25,
            calories: 680,
            servings: 2,
            ingredients: ["spaghetti", "pancetta", "eggs", "parmesan", "black pepper", "salt"],
            instructions: "Cook pasta. Fry pancetta. Mix eggs and parmesan. Toss hot pasta off heat with egg mixture.",
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: true,
            tags: ["pasta", "italian", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Butter Chicken",
            imageURL: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600",
            cuisine: "Indian",
            mealType: .dinner,
            prepTime: 45,
            calories: 620,
            servings: 4,
            ingredients: ["chicken thighs", "butter", "tomato puree", "cream", "garlic", "ginger", "garam masala", "cumin", "rice"],
            instructions: "Marinate chicken. Sauté garlic and ginger. Add spices and tomato. Simmer chicken. Finish with cream and butter.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["curry", "indian", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Tacos",
            imageURL: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600",
            cuisine: "Mexican",
            mealType: .dinner,
            prepTime: 30,
            calories: 560,
            servings: 3,
            ingredients: ["corn tortillas", "beef mince", "taco seasoning", "cheddar", "sour cream", "salsa", "avocado", "lime"],
            instructions: "Brown beef with seasoning. Warm tortillas. Fill with beef and toppings. Serve with lime.",
            authorUsername: "mexicanfeast",
            isPublic: true,
            isTrending: true,
            tags: ["mexican", "tacos", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Salmon Teriyaki",
            imageURL: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600",
            cuisine: "Japanese",
            mealType: .dinner,
            prepTime: 20,
            calories: 490,
            servings: 2,
            ingredients: ["salmon fillets", "soy sauce", "mirin", "sake", "sugar", "steamed rice", "sesame seeds", "spring onion"],
            instructions: "Mix teriyaki sauce. Marinate salmon 15 mins. Pan fry skin-side down. Glaze with sauce. Serve over rice.",
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: true,
            tags: ["japanese", "fish", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Bourguignon",
            imageURL: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600",
            cuisine: "French",
            mealType: .dinner,
            prepTime: 180,
            calories: 720,
            servings: 6,
            ingredients: ["beef chuck", "red wine", "bacon", "mushrooms", "pearl onions", "carrots", "thyme", "garlic", "beef stock"],
            instructions: "Brown beef and bacon. Deglaze with wine. Add vegetables and stock. Braise in oven at 160°C for 2.5 hours.",
            authorUsername: "chefpierre",
            isPublic: true,
            isTrending: false,
            tags: ["french", "slow cook", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Tikka Masala",
            imageURL: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
            cuisine: "Indian",
            mealType: .dinner,
            prepTime: 50,
            calories: 640,
            servings: 4,
            ingredients: ["chicken breast", "yoghurt", "tikka masala paste", "canned tomatoes", "cream", "garlic", "ginger", "naan"],
            instructions: "Marinate chicken in yoghurt and spices. Grill. Simmer in tomato and cream sauce. Serve with naan.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: true,
            tags: ["indian", "curry", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Margherita Pizza",
            imageURL: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 60,
            calories: 700,
            servings: 2,
            ingredients: ["pizza dough", "san marzano tomatoes", "fresh mozzarella", "basil", "olive oil", "salt"],
            instructions: "Stretch dough. Spread crushed tomatoes. Top with torn mozzarella. Bake at 250°C for 10 mins. Add fresh basil.",
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: true,
            tags: ["pizza", "italian", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Lamb Kofta",
            imageURL: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600",
            cuisine: "Middle Eastern",
            mealType: .dinner,
            prepTime: 35,
            calories: 580,
            servings: 4,
            ingredients: ["lamb mince", "onion", "cumin", "coriander", "cinnamon", "garlic", "flatbread", "tzatziki", "salad"],
            instructions: "Mix lamb with spices. Shape onto skewers. Grill until charred. Serve with flatbread and tzatziki.",
            authorUsername: "spiceroute",
            isPublic: true,
            isTrending: false,
            tags: ["middle eastern", "grilled", "lamb"]
        ),
        Recipe(
            id: UUID(),
            title: "Mushroom Risotto",
            imageURL: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600",
            cuisine: "Italian",
            mealType: .dinner,
            prepTime: 45,
            calories: 590,
            servings: 2,
            ingredients: ["arborio rice", "mixed mushrooms", "white wine", "parmesan", "butter", "shallots", "garlic", "thyme", "stock"],
            instructions: "Sauté shallots and garlic. Toast rice. Add wine. Add stock ladle by ladle stirring constantly. Fold in butter and parmesan.",
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["italian", "vegetarian", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Green Thai Curry",
            imageURL: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600",
            cuisine: "Thai",
            mealType: .dinner,
            prepTime: 35,
            calories: 550,
            servings: 3,
            ingredients: ["chicken", "green curry paste", "coconut milk", "thai eggplant", "bamboo shoots", "kaffir lime leaves", "fish sauce", "jasmine rice"],
            instructions: "Fry curry paste in coconut cream. Add chicken. Pour in coconut milk. Add vegetables and simmer. Serve with rice.",
            authorUsername: "bangkokbowls",
            isPublic: true,
            isTrending: true,
            tags: ["thai", "curry", "spicy"]
        ),
        Recipe(
            id: UUID(),
            title: "BBQ Pulled Pork",
            imageURL: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600",
            cuisine: "American",
            mealType: .dinner,
            prepTime: 360,
            calories: 680,
            servings: 6,
            ingredients: ["pork shoulder", "bbq sauce", "brown sugar", "paprika", "garlic powder", "onion powder", "brioche buns", "coleslaw"],
            instructions: "Rub pork with spice mix. Slow cook 6 hours at 140°C. Shred with forks. Toss in BBQ sauce. Serve in brioche buns.",
            authorUsername: "pitmaster_aus",
            isPublic: true,
            isTrending: true,
            tags: ["american", "slow cook", "bbq"]
        ),
        Recipe(
            id: UUID(),
            title: "Prawn Stir Fry",
            imageURL: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
            cuisine: "Chinese",
            mealType: .dinner,
            prepTime: 20,
            calories: 420,
            servings: 2,
            ingredients: ["prawns", "bok choy", "garlic", "ginger", "oyster sauce", "soy sauce", "sesame oil", "rice", "spring onion"],
            instructions: "Stir fry garlic and ginger. Add prawns until pink. Add bok choy and sauce. Toss and serve over rice.",
            authorUsername: "wokmaster",
            isPublic: true,
            isTrending: false,
            tags: ["chinese", "quick", "seafood"]
        ),
        Recipe(
            id: UUID(),
            title: "Moussaka",
            imageURL: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600",
            cuisine: "Greek",
            mealType: .dinner,
            prepTime: 90,
            calories: 660,
            servings: 6,
            ingredients: ["eggplant", "lamb mince", "tomato", "cinnamon", "allspice", "bechamel sauce", "parmesan", "onion", "garlic"],
            instructions: "Fry eggplant. Make spiced lamb sauce. Layer eggplant and meat. Top with bechamel and cheese. Bake 45 mins.",
            authorUsername: "mediterraneankitchen",
            isPublic: true,
            isTrending: false,
            tags: ["greek", "baked", "comfort"]
        ),
        Recipe(
            id: UUID(),
            title: "Chicken Schnitzel",
            imageURL: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600",
            cuisine: "Australian",
            mealType: .dinner,
            prepTime: 30,
            calories: 610,
            servings: 2,
            ingredients: ["chicken breast", "breadcrumbs", "eggs", "flour", "lemon", "chips", "salad", "salt", "pepper"],
            instructions: "Pound chicken flat. Coat in flour, egg and breadcrumbs. Pan fry until golden. Serve with chips and lemon.",
            authorUsername: "aussiegrill",
            isPublic: true,
            isTrending: true,
            tags: ["australian", "fried", "classic"]
        ),
        Recipe(
            id: UUID(),
            title: "Vegetable Dumplings",
            imageURL: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600",
            cuisine: "Chinese",
            mealType: .dinner,
            prepTime: 50,
            calories: 380,
            servings: 4,
            ingredients: ["dumpling wrappers", "cabbage", "shiitake mushrooms", "ginger", "garlic", "soy sauce", "sesame oil", "spring onion"],
            instructions: "Mix filling. Place in wrappers and seal. Steam or pan fry until golden. Serve with dipping sauce.",
            authorUsername: "wokmaster",
            isPublic: true,
            isTrending: false,
            tags: ["chinese", "dumplings", "vegetarian"]
        ),
        Recipe(
            id: UUID(),
            title: "Beef Rendang",
            imageURL: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600",
            cuisine: "Malaysian",
            mealType: .dinner,
            prepTime: 120,
            calories: 690,
            servings: 4,
            ingredients: ["beef chuck", "coconut milk", "lemongrass", "galangal", "turmeric", "chili", "kaffir lime leaves", "toasted coconut", "rice"],
            instructions: "Blend spice paste. Brown beef. Add coconut milk and paste. Simmer 1.5 hours until sauce is dry and beef is coated.",
            authorUsername: "asianfusionkitchen",
            isPublic: true,
            isTrending: true,
            tags: ["malaysian", "slow cook", "spicy"]
        ),

        // MARK: — Snacks (8)
        Recipe(
            id: UUID(),
            title: "Hummus & Veggies",
            imageURL: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=600",
            cuisine: "Middle Eastern",
            mealType: .snack,
            prepTime: 10,
            calories: 220,
            servings: 2,
            ingredients: ["chickpeas", "tahini", "lemon", "garlic", "olive oil", "paprika", "carrot", "celery", "cucumber"],
            instructions: "Blend chickpeas, tahini, lemon and garlic until smooth. Drizzle with olive oil and paprika. Serve with cut vegetables.",
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "vegan", "dip"]
        ),
        Recipe(
            id: UUID(),
            title: "Energy Balls",
            imageURL: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 15,
            calories: 180,
            servings: 12,
            ingredients: ["rolled oats", "peanut butter", "honey", "dark chocolate chips", "chia seeds", "vanilla"],
            instructions: "Mix all ingredients. Roll into balls. Refrigerate 30 mins to set.",
            authorUsername: "mealprepsunday",
            isPublic: true,
            isTrending: true,
            tags: ["snack", "no-bake", "meal prep"]
        ),
        Recipe(
            id: UUID(),
            title: "Guacamole & Chips",
            imageURL: "https://images.unsplash.com/photo-1518181835702-6eef8b4b2113?w=600",
            cuisine: "Mexican",
            mealType: .snack,
            prepTime: 10,
            calories: 280,
            servings: 4,
            ingredients: ["avocado", "lime", "coriander", "red onion", "jalapeño", "tomato", "salt", "corn chips"],
            instructions: "Mash avocado. Mix in lime juice, onion, jalapeño and coriander. Season and serve with corn chips.",
            authorUsername: "mexicanfeast",
            isPublic: true,
            isTrending: true,
            tags: ["mexican", "dip", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Protein Smoothie",
            imageURL: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 5,
            calories: 340,
            servings: 1,
            ingredients: ["banana", "protein powder", "almond milk", "peanut butter", "honey", "ice"],
            instructions: "Blend all ingredients until smooth. Serve immediately.",
            authorUsername: "fitmeals",
            isPublic: true,
            isTrending: false,
            tags: ["smoothie", "protein", "quick"]
        ),
        Recipe(
            id: UUID(),
            title: "Baked Kale Chips",
            imageURL: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 20,
            calories: 120,
            servings: 2,
            ingredients: ["kale", "olive oil", "salt", "nutritional yeast", "garlic powder"],
            instructions: "Tear kale into pieces. Toss with oil and seasoning. Bake at 175°C for 15 mins until crispy.",
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "vegan", "low calorie"]
        ),
        Recipe(
            id: UUID(),
            title: "Caprese Skewers",
            imageURL: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600",
            cuisine: "Italian",
            mealType: .snack,
            prepTime: 10,
            calories: 200,
            servings: 4,
            ingredients: ["cherry tomatoes", "fresh mozzarella balls", "basil", "balsamic glaze", "olive oil", "salt"],
            instructions: "Thread tomato, mozzarella and basil onto skewers. Drizzle with olive oil and balsamic glaze. Season.",
            authorUsername: "pastanonna",
            isPublic: true,
            isTrending: false,
            tags: ["italian", "snack", "party"]
        ),
        Recipe(
            id: UUID(),
            title: "Edamame with Sea Salt",
            imageURL: "https://images.unsplash.com/photo-1550951234-8f8c7e5a7e3b?w=600",
            cuisine: "Japanese",
            mealType: .snack,
            prepTime: 10,
            calories: 150,
            servings: 2,
            ingredients: ["edamame pods", "sea salt", "sesame oil"],
            instructions: "Boil edamame in salted water for 5 mins. Drain and toss with sea salt and a drizzle of sesame oil.",
            authorUsername: "tokyotable",
            isPublic: true,
            isTrending: false,
            tags: ["japanese", "snack", "healthy"]
        ),
        Recipe(
            id: UUID(),
            title: "Apple Slices with Almond Butter",
            imageURL: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600",
            cuisine: "American",
            mealType: .snack,
            prepTime: 5,
            calories: 210,
            servings: 1,
            ingredients: ["apple", "almond butter", "cinnamon", "honey"],
            instructions: "Slice apple. Serve with almond butter for dipping. Dust with cinnamon and drizzle honey if desired.",
            authorUsername: "cleaneatclub",
            isPublic: true,
            isTrending: false,
            tags: ["snack", "quick", "healthy"]
        ),
    ]

    static var trending: [Recipe] {
        all.filter { $0.isTrending }
    }

    static func byMealType(_ type: MealType) -> [Recipe] {
        all.filter { $0.mealType == type.rawValue }
    }

    static func byCuisine(_ cuisine: String) -> [Recipe] {
        all.filter { $0.cuisine == cuisine }
    }

    static func search(_ query: String) -> [Recipe] {
        let q = query.lowercased()
        return all.filter {
            $0.name.lowercased().contains(q) ||
            $0.cuisine.lowercased().contains(q) ||
            $0.tags.contains(where: { $0.lowercased().contains(q) })
        }
    }
}
